application: hs-paste
version: 1
runtime: python
api_version: 1

handlers:
- url: /style
  static_dir: style

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /.*
  script: hs-paste.py
  login: required


